"""IntEnum transcription of the CABT engine's real enums.

Source: engine/Types.h — verified against the actual engine source.
"""

from enum import IntEnum
from typing import TypeVar

EnumT = TypeVar("EnumT", bound=IntEnum)


def safe(cls: type[EnumT], value: int | None) -> EnumT | int | None:  # noqa: UP047
    """Return the enum member for ``value``, or the raw int if unknown."""
    if value is None:
        return None
    try:
        return cls(value)
    except ValueError:
        return value


class SelectType(IntEnum):
    MAIN = 0
    CARD = 1
    ATTACHED_CARD = 2
    CARD_OR_ATTACHED_CARD = 3
    ENERGY = 4
    SKILL = 5
    ATTACK = 6
    EVOLVE = 7
    COUNT = 8
    YES_NO = 9
    SPECIAL_CONDITION = 10


class OptionType(IntEnum):
    NUMBER = 0
    YES = 1
    NO = 2
    CARD = 3
    TOOL_CARD = 4
    ENERGY_CARD = 5
    ENERGY = 6
    PLAY = 7
    ATTACH = 8
    EVOLVE = 9
    ABILITY = 10
    DISCARD = 11
    RETREAT = 12
    ATTACK = 13
    END = 14
    SKILL = 15
    SPECIAL_CONDITION = 16


class SelectContext(IntEnum):
    MAIN = 0
    SETUP_ACTIVE_POKEMON = 1
    SETUP_BENCH_POKEMON = 2
    SWITCH = 3
    TO_ACTIVE = 4
    TO_BENCH = 5
    TO_FIELD = 6
    TO_HAND = 7
    DISCARD = 8
    TO_DECK = 9
    TO_DECK_BOTTOM = 10
    TO_PRIZE = 11
    NOT_MOVE = 12
    DAMAGE_COUNTER = 13
    DAMAGE_COUNTER_ANY = 14
    DAMAGE = 15
    REMOVE_DAMAGE_COUNTER = 16
    HEAL = 17
    EVOLVES_FROM = 18
    EVOLVES_TO = 19
    DEVOLVE = 20
    ATTACH_FROM = 21
    ATTACH_TO = 22
    DETACH_FROM = 23
    LOOK = 24
    EFFECT_TARGET = 25
    DISCARD_ENERGY_CARD = 26
    DISCARD_TOOL_CARD = 27
    SWITCH_ENERGY_CARD = 28
    DISCARD_CARD_OR_ATTACHED_CARD = 29
    DISCARD_ENERGY = 30
    TO_HAND_ENERGY = 31
    TO_DECK_ENERGY = 32
    SWITCH_ENERGY = 33
    SKILL_ORDER = 34
    ATTACK = 35
    DISABLE_ATTACK = 36
    EVOLVE = 37
    DRAW_COUNT = 38
    DAMAGE_COUNTER_COUNT = 39
    REMOVE_DAMAGE_COUNTER_COUNT = 40
    IS_FIRST = 41
    MULLIGAN = 42
    ACTIVATE = 43
    FIRST_EFFECT = 44
    MORE_DEVOLVE = 45
    COIN_HEAD = 46
    AFFECT_SPECIAL_CONDITION = 47
    RECOVER_SPECIAL_CONDITION = 48


class EffectType(IntEnum):
    NO_EFFECT = 0
    SELECT_CARD = 1
    FOR_EACH = 2
    KO = 3
    TO_HAND = 4
    PRIZE_TO_HAND = 5
    TO_HAND_REVERSE = 6
    TO_HAND_WITH_ATTACH = 7
    TO_TRASH = 8
    TO_DECK = 9
    TO_DECK_WITH_ATTACH = 10
    TO_DECK_REVERSE = 11
    LOOK_TO_DECK_REVERSE = 12
    TO_DECK_AND_SHUFFLE = 13
    TO_DECK_REVERSE_AND_SHUFFLE = 14
    TO_DECK_BOTTOM = 15
    TO_DECK_BOTTOM_REVERSE = 16
    TO_DECK_BOTTOM_CLOSE = 17
    TO_ACTIVE_AND_TRASH_ACTIVE = 18
    TO_BENCH = 19
    TO_PRIZE = 20
    TO_LOOKING = 21
    TO_PLAYING_FIRST = 22
    SWITCH = 23
    SWITCH_DECK = 24
    NOT_MOVE = 25
    LOOK_DECK = 26
    LOOK_DECK_REVERSE = 27
    LOOK_DECK_BOTTOM = 28
    LOOK_AND_RETURN = 29
    DAMAGE_COUNTER = 30
    DAMAGE_COUNTER_REMOVED = 31
    DAMAGE_COUNTER_DAMAGED = 32
    DAMAGE_COUNTER_ANY = 33
    DAMAGE_COUNTER_DOUBLE = 34
    DAMAGE_COUNTER_HP = 35
    DAMAGE_COUNTER_SWITCH_ANY = 36
    DAMAGE_COUNTER_TYPE_ENERGY_COUNT_ME = 37
    ATTACK_DAMAGE = 38
    ATTACK_DAMAGE_MULTI = 39
    ATTACK_DAMAGE_COIN = 40
    REMOVE_DAMAGE_COUNTER = 41
    REMOVE_DAMAGE_COUNTER_ALL = 42
    HEAL = 43
    HEAL_ALL = 44
    HEAL_SAND = 45
    RESET_HP = 46
    DRAIN = 47
    DEVOLVE = 48
    DEVOLVE_ANY = 49
    TRANSFORM_DECK = 50
    TRANSFORM_TRASH = 51
    EXCHANGE_SELECTED = 52
    KO_PRIZE_CHANGE_ALWAYS = 53
    KO_PRIZE_CHANGE = 54
    KO_PRIZE_DECREASE_ONCE = 55
    SELECT_EVOLVES_FROM = 56
    EVOLVES_TO_EACH = 57
    SELECT_EVOLVES_TO = 58
    EVOLVES_FROM_EACH = 59
    SELECT_ATTACH_FROM = 60
    ATTACH_TO_EACH = 61
    SELECT_ATTACH_TO = 62
    ATTACH_ENERGY_ME = 63
    ATTACH_SELECTED_CARD = 64
    SWITCH_SELECTED_CARD = 65
    ATTACH_FROM_EACH = 66
    SELECT_SWITCH_ENERGY = 67
    SELECT_SWITCH_ENERGY_CARD = 68
    ENERGY_SWITCH_EACH = 69
    DELAY_EFFECT = 70
    COIN = 71
    COIN_UNTIL_TAIL = 72
    ATTACK_DAMAGE_CHANGE = 73
    ATTACK_DAMAGE_CHANGE_TARGET_COUNT = 74
    EFFECT_DAMAGE_CHANGE_TARGET_COUNT = 75
    ATTACK_DAMAGE_CHANGE_ENERGY_COUNT = 76
    EFFECT_DAMAGE_CHANGE_ENERGY_COUNT = 77
    ATTACK_DAMAGE_CHANGE_TYPE_ENERGY_COUNT = 78
    EFFECT_DAMAGE_CHANGE_TYPE_ENERGY_COUNT = 79
    ATTACK_DAMAGE_CHANGE_ENERGY_COUNT_COIN = 80
    EFFECT_DAMAGE_CHANGE_TYPE_ENERGY_COUNT_COIN = 81
    ATTACK_DAMAGE_CHANGE_COIN = 82
    ATTACK_DAMAGE_CHANGE_COIN_UNTIL_TAIL = 83
    ATTACK_DAMAGE_CHANGE_TARGET_COUNT_COIN = 84
    ATTACK_DAMAGE_CHANGE_TARGET_COUNT_ENEMY_COIN = 85
    ATTACK_DAMAGE_CHANGE_TAKEN_PRIZE = 86
    EFFECT_DAMAGE_CHANGE_TAKEN_PRIZE = 87
    ATTACK_DAMAGE_CHANGE_DAMAGE_COUNTER = 88
    EFFECT_DAMAGE_CHANGE_DAMAGE_COUNTER = 89
    ATTACK_DAMAGE_CHANGE_PUT_DAMAGE_COUNTER = 90
    ATTACK_DAMAGE_CHANGE_RETREAT_COST = 91
    ATTACK_DAMAGE_CHANGE_TYPE_COUNT = 92
    ATTACK_DAMAGE_CHANGE_SPECIAL_CONDITION_COUNT = 93
    ATTACK_DAMAGE_CHANGE_TAKE_ATTACK_DAMAGE_PRE_TURN = 94
    ATTACK_DAMAGE_CHANGE_PRE_TURN_TAKE_PRIZE_COUNT = 95
    BURN = 96
    POISON = 97
    POISON_8 = 98
    POISON_16 = 99
    SLEEP = 100
    CONFUSE = 101
    PARALYZE = 102
    RECOVER_SPECIAL_CONDITION = 103
    RECOVER_SPECIAL_CONDITION_SINGLE = 104
    DRAW = 105
    DRAW_TARGET_COUNT = 106
    DRAW_PRIZE_COUNT = 107
    DRAW_UNTIL = 108
    DRAW_UNTIL_PSYCHIC = 109
    DRAW_MIRROR = 110
    DECK_TO_TRASH = 111
    DECK_TO_TRASH_COIN_UNTIL_TAIL = 112
    DECK_BOTTOM_TO_TRASH = 113
    DECK_TO_PRIZE = 114
    SHUFFLE = 115
    EFFECT_WIN = 116
    FAIL_RETREAT = 117
    TURN_END = 118
    DAMAGE_CHANGE_THIS_TURN = 119
    DAMAGE_CHANGE_EX_THIS_TURN = 120
    PLAYER_DAMAGE_CHANGE = 121
    PLAYER_DAMAGE_CHANGE_EX = 122
    PLAYER_DAMAGE_CHANGE_MY_FIGHTING = 123
    TAKE_PRIZE_COUNT_CHANGE_TERASTAL_ATTACK_KO_ACTIVE = 124
    TAKE_PRIZE_COUNT_CHANGE_N_ATTACK_KO_ACTIVE = 125
    TAKE_DAMAGE_CHANGE_NEXT_ENEMY_TURN = 126
    NO_DAMAGE_LESS_EQUAL_ATTACK_NEXT_ENEMY_TURN = 127
    NO_DAMAGE_AND_EFFECT_ATTACK_NEXT_ENEMY_TURN = 128
    NO_DAMAGE_AND_EFFECT_ENEMY_ATTACK_NEXT_ENEMY_TURN = 129
    NO_DAMAGE_AND_EFFECT_ENEMY_EX_ATTACK_NEXT_ENEMY_TURN = 130
    NO_DAMAGE_ATTACK_NEXT_ENEMY_TURN = 131
    NO_DAMAGE_BASIC_ATTACK_NEXT_ENEMY_TURN = 132
    NO_DAMAGE_BASIC_COLOR_ATTACK_NEXT_ENEMY_TURN = 133
    NO_DAMAGE_ABILITY_ATTACK_NEXT_ENEMY_TURN = 134
    NO_WEAKNESS_NEXT_ENEMY_TURN = 135
    CANNOT_USE_THIS_ATTACK_NEXT_TURN = 136
    DAMAGE_CHANGE_MY_ATTACK_NEXT_TURN = 137
    DAMAGE_CHANGE_ACTIVE_NEXT_TURN = 138
    DAMAGE_CHANGE_NEXT_TURN = 139
    ATTACK_COST_CHANGE_NEXT_TURN = 140
    RETREAT_COST_CHANGE_NEXT_TURN = 141
    CANNOT_RETREAT_NEXT_TURN = 142
    CANNOT_HAND_ATTACH_ENERGY_NEXT_TURN = 143
    CANNOT_ATTACK_NEXT_TURN = 144
    CANNOT_ATTACK_LESS_EQUAL_ENERGY_2_NEXT_TURN = 145
    ATTACK_COIN_NEXT_TURN = 146
    ATTACK_COIN_2_NEXT_TURN = 147
    CANNOT_USE_SELECTED_ATTACK = 148
    METAL_DAMAGE_CHANGE_NEXT_TURN = 149
    CANNOT_ATTACK_LESS_EQUAL_ENERGY_2_NEXT_TURN_PLAYER = 150
    CANNOT_PLAY_ITEM_NEXT_TURN = 151
    CANNOT_PLAY_SUPPORTER_NEXT_TURN = 152
    CANNOT_PLAY_STADIUM_NEXT_TURN = 153
    CANNOT_PLAY_SPECIAL_ENERGY_NEXT_TURN = 154
    CANNOT_EVOLVE_NEXT_TURN = 155
    CANNOT_RETREAT_POISON = 156
    TAKE_DAMAGE_CHANGE_NEXT_MY_TURN_ENEMY = 157
    CANNOT_USE_THIS_ATTACK_NON_ACTIVE = 158
    SELECT_ACTIVATE = 159
    SELECT_EFFECT = 160
    FAIL_ATTACK = 161
    CANCEL_FAIL_ATTACK = 162
    BREAK_IF_COIN_HEAD = 163
    BREAK_IF_COIN_TAIL = 164
    BREAK_IF_COIN_TAIL_MULTI = 165
    SKIP_IF_COIN_TAIL = 166
    POST_EFFECT_ACTIVATE = 167
    BREAK_IF_NOT_POST_EFFECT_ACTIVATED = 168
    SELECT_POISON_BURN_CONFUSE = 169
    SELECT_SPECIAL_CONDITION = 170
    CONTINUAL_EFFECT_SEPARATOR = 171
    MAX_HP_CHANGE = 172
    MAX_HP_CHANGE_FIGHTING = 173
    DAMAGE_CHANGE = 174
    DAMAGE_CHANGE_ACTIVE = 175
    DAMAGE_CHANGE_EX = 176
    DAMAGE_CHANGE_ABILITY = 177
    DAMAGE_CHANGE_EVOLVED = 178
    DAMAGE_CHANGE_ENEMY_TAKEN_PRIZE = 179
    TAKE_DAMAGE_CHANGE = 180
    TAKE_ENEMY_ATTACK_DAMAGE_CHANGE = 181
    TAKE_ENEMY_ABILITY_POKEMON_ATTACK_DAMAGE_CHANGE = 182
    TAKE_ENEMY_FIRE_OR_WATER_POKEMON_ATTACK_DAMAGE_CHANGE = 183
    TAKE_ENEMY_4_TYPE_POKEMON_ATTACK_DAMAGE_CHANGE = 184
    NO_DAMAGE_GREATER_EQUAL = 185
    RETREAT_COST_CHANGE = 186
    ATTACK_COST_CHANGE_COLORLESS = 187
    ATTACK_COST_DOWN = 188
    ATTACK_COST_DOWN_COLORLESS_TARGET_COUNT = 189
    ATTACK_COST_DOWN_COLORLESS_OWN_ATTACK_ENEMY_TAKEN_PRIZE = 190
    ADD_ENERGY_TYPE = 191
    SET_WEAKNESS = 192
    NO_ABILITY = 193
    NO_KO_ME_ABILITY = 194
    NO_DAMAGE_ENEMY_ATTACK = 195
    NO_DAMAGE_ENEMY_ABILITY_POKEMON_ATTACK = 196
    NO_DAMAGE_ENEMY_EX_ATTACK = 197
    NO_DAMAGE_ENEMY_BASIC_EX_ATTACK = 198
    NO_DAMAGE_AND_EFFECT_ENEMY_TERASTAL_ATTACK = 199
    NO_DAMAGE_AND_EFFECT_ENEMY_SPECIAL_ENERGY_ATTACK = 200
    NO_EFFECT_ENEMY_ATTACK = 201
    NO_DAMAGE_AND_EFFECT_ENEMY_ATTACK = 202
    NO_EFFECT_ENEMY_ITEM = 203
    NO_EFFECT_ENEMY_SUPPORTER = 204
    NO_DAMAGE_COUNTER_ENEMY_ATTACK_ABILITY = 205
    NO_ENEMY_ABILITY = 206
    NO_SPECIAL_CONDITION = 207
    NO_SLEEP_PARALYZE_CONFUSE = 208
    NO_SLEEP = 209
    NO_RETREAT_COST = 210
    NO_PRIZE_EX = 211
    NOT_RECOVER_CONFUSE_EVOLVE = 212
    CAN_USE_PRE_EVOLUTION_ATTACK = 213
    CAN_EVOLVE_APPEAR_TURN = 214
    CAN_EVOLVE_GRASS_APPEAR_TURN = 215
    CAN_ATTACK_FIRST = 216
    CANNOT_RETREAT = 217
    CANNOT_ATTACK = 218
    CANNOT_TO_HAND = 219
    CANNOT_MOVE_DAMAGE_COUNTER = 220
    ATTACK_ENERGY_COLORLESS_ONE = 221
    ATTACK_ENERGY_PSYCHIC_ONE = 222
    DOUBLE_GRASS_ENERGY = 223
    NO_DAMAGE_COIN = 224
    KO_BY_DAMAGE_TO_HAND = 225
    BASIC_PRIZE_PLUS_1 = 226
    DOUBLE_ATTACK = 227
    TOOL_2 = 228
    TOOL_4 = 229
    TECHNICAL_MACHINE = 230
    SPECIAL_FLAG_TOOL = 231
    RAINBOW_DNA = 232
    CAN_PLAY = 233
    POISON_DAMAGE_CHANGE = 234
    BURN_DAMAGE_CHANGE = 235
    POISON_DAMAGE_CHANGE_NOT_DARKNESS = 236
    BENCH_CAPACITY = 237
    CANNOT_PLAY_ITEM = 238
    CANNOT_PLAY_STADIUM = 239
    CANNOT_PLAY_TOOL = 240
    CANNOT_PLAY_ACE_SPEC = 241
    CANNOT_PLAY_ABILITY_POKEMON_NOT_ROCKET = 242
    CANNOT_TRASH_TO_HAND_ABILITY_OR_TRAINERS = 243
    NO_TOOL_EFFECT = 244


class TargetType(IntEnum):
    ALL = 0
    HP = 1
    MAX_HP = 2
    RETREAT_COST = 3
    ENERGY_TYPE = 4
    ENERGY_TYPE_2 = 5
    RESISTANCE = 6
    POKEMON_CARD = 7
    BASIC_POKEMON = 8
    EVOLVED_POKEMON = 9
    STAGE1 = 10
    STAGE2 = 11
    BASIC_ENERGY = 12
    SPECIAL_ENERGY = 13
    ENERGY_CARD = 14
    ITEM = 15
    TOOL = 16
    SUPPORTER = 17
    STADIUM = 18
    TRAINER = 19
    CARD_ID = 20
    POKEMON_OR_BASIC_ENERGY = 21
    BASIC_POKEMON_OR_BASIC_ENERGY = 22
    NOT_RULE_POKEMON_CARD_OR_BASIC_ENERGY = 23
    ENERGY_TYPE_POKEMON_OR_STADIUM = 24
    ITEM_OR_TOOL = 25
    ENEMY_TOOL_OR_SPECIAL_ENERGY_OR_STADIUM = 26
    ETHAN_POKEMON_OR_BASIC_FIRE_ENERGY = 27
    HAS_ABILITY = 28
    HAS_ABILITY_NAME = 29
    HAS_ATTACK_NAME = 30
    RULE_POKEMON = 31
    NOT_RULE_POKEMON = 32
    EX = 33
    MEGA_EX = 34
    TERASTAL = 35
    ANCIENT = 36
    FUTURE = 37
    HOP = 38
    LILLIE = 39
    IONO = 40
    N = 41
    ETHAN = 42
    CYNTHIA = 43
    MISTY = 44
    ARVEN = 45
    STEVEN = 46
    MARNIE = 47
    ERIKA = 48
    LARRY = 49
    TEAM_ROCKET = 50
    SILCOON_OR_CASCOON = 51
    KOFFING_OR_WEEZING = 52
    HONEDGE_OR_DOUBLADE_OR_AEGISLASH = 53
    NAME = 54
    NAME_CONTAINS = 55
    CAN_EVOLVE = 56
    CAN_EVOLVE_2 = 57
    CAN_EVOLVE_ME = 58
    CAN_EVOLVE_CONTEXT_CARD = 59
    CAN_EVOLVES_TO_CONTEXT_CARD = 60
    CAN_EVOLVE_FIELD = 61
    CAN_EVOLVE_FIELD_NOT_APPEAR_THIS_TURN = 62
    EVOLVED = 63
    EVOLVED_THIS_TURN_NAME = 64
    NOT_APPEAR_THIS_TURN = 65
    HEAL_THIS_TURN = 66
    ATTACHED_ME = 67
    ATTACHED_EFFECTED = 68
    ATTACHED_TRIGGER_SUBJECT = 69
    ATTACHED_TRIGGER_OBJECT = 70
    ATTACHED_CONTEXT_CARD = 71
    ATTACHED_ACTIVE_POKEMON = 72
    ATTACHED_BENCH_POKEMON = 73
    IS_ATTACHED_ENERGY = 74
    ATTACHED_ENERGY_COUNT = 75
    IS_ATTACHED_SPECIAL_ENERGY = 76
    IS_ATTACHED_ENERGY_TYPE = 77
    IS_ATTACHED_ENERGY_2_TYPE = 78
    IS_ATTACHED_ENERGY_NAME = 79
    IS_ATTACHED_TOOL = 80
    IS_ATTACHED_TOOL_NAME = 81
    IS_ATTACHED_TOOL_OR_SPECIAL_ENERGY = 82
    NOT_CONTEXT_CARD_ATTACHED_POKEMON = 83
    NOT_SELECTED_LIST_ATTACHED_POKEMON = 84
    ENERGY_TYPE_ATTACHED = 85
    REVERSE = 86
    AREA = 87
    TRIGGER_SUBJECT = 88
    TRIGGER_OBJECT = 89
    DAMAGE_COUNTER = 90
    MIN_HP = 91
    SAME_TYPE_ENEMY = 92
    SPECIAL_CONDITION = 93
    SPECIAL_CONDITION_OR_DAMAGED = 94
    POISON = 95
    BURN = 96
    CONFUSE = 97
    POISON_OR_BURN = 98
    BENCH_TO_ACTIVE_THIS_TURN = 99
    SAME_NAME_ENEMY_FIELD = 100
    NOT_CHECKED = 101


class ConditionType(IntEnum):
    ALWAYS = 0
    ANY_TARGET_AFTER_EFFECT = 1
    COUNT_TARGET = 2
    COUNT_TARGET_2 = 3
    COUNT_TARGET_ME_OR_ENEMY = 4
    COMPARE_COUNT_TARGET_ME_ENEMY = 5
    COUNT_ENERGY = 6
    COUNT_ENERGY_TYPE = 7
    COMPARE_COUNT_ENERGY_ME_ENEMY = 8
    ATTACK_ENERGY_EXTRA = 9
    NOT_FULL_BENCH = 10
    MY_TURN = 11
    TURN = 12
    KO_PRE_ENEMY_TURN = 13
    KO_PRE_ENEMY_TURN_TEAM_ROCKET = 14
    KO_ATTACK_DAMAGE_PRE_ENEMY_TURN = 15
    KO_ATTACK_DAMAGE_ETHAN_PRE_ENEMY_TURN = 16
    KO_ATTACK_DAMAGE_HOP_PRE_ENEMY_TURN = 17
    NO_SAME_NAME_SKILL_THIS_TURN = 18
    SAME_ATTACK_PRE_MY_TURN = 19
    COIN_HEAD_COUNT = 20
    ATTACH_ACTIVE = 21
    MYSTERY_GARDEN = 22
    LOVE_BALL = 23


class TargetPlayer(IntEnum):
    NONE = 0
    ME = 1
    ENEMY = 2
    BOTH = 3


class ComparatorType(IntEnum):
    EQUAL = 0
    GREATER_EQUAL = 1
    LESS_EQUAL = 2
    NOT_EQUAL = 3
    GREATER = 4
    LESS = 5


class EffectSelectType(IntEnum):
    ALL = 0
    CARD_COUNT = 1
    MAX_CARD_COUNT = 2
    CARD_UNTIL = 3
    MAX_CARD_UNTIL = 4
    ENERGY = 5
    MAX_ENERGY_CARD = 6
    TOOL_CARD = 7
    CARD_OR_ATTACHED_CARD_COUNT = 8
    EVOLVE = 9
    EVOLVE_2 = 10


class TriggerType(IntEnum):
    NONE = 0
    TURN_END = 1
    POKEMON_CHECKUP = 2
    HAND_TO_BENCH = 3
    ACTIVE_TO_BENCH = 4
    TO_BENCH_MY_TURN = 5
    BENCH_TO_ACTIVE = 6
    DECK_TO_TRASH_ENEMY_EFFECT = 7
    EVOLVE_FROM_HAND = 8
    ENERGY_ATTACH_FROM_HAND = 9
    DAMAGED_ENEMY_ATTACK = 10
    DAMAGED_ENEMY_ATTACK_ACTIVE = 11
    PRE_KO = 12
    PRE_KO_FULL = 13
    PRE_KO_FULL_ENEMY = 14
    KO = 15
    KO_ENEMY_ATTACK_DAMAGE = 16
    KO_ENEMY_EX_ATTACK_DAMAGE = 17
    KO_ENEMY_ATTACK_DAMAGE_ACTIVE = 18
    PRE_RETREAT = 19
    ATTACH = 20


class SkillType(IntEnum):
    ABILITY = 0
    PLAY = 1
    ATTACH = 2


class EnergyType(IntEnum):
    COLORLESS = 0
    GRASS = 1
    FIRE = 2
    WATER = 3
    LIGHTNING = 4
    PSYCHIC = 5
    FIGHTING = 6
    DARKNESS = 7
    METAL = 8
    DRAGON = 9
    RAINBOW = 10
    TEAM_ROCKET = 11
    PSYCHIC_DARKNESS = 12


class PokemonType(IntEnum):
    NOT_POKEMON = 0
    NORMAL = 1
    POKEMON_ITEM = 2
    EX = 3
    MEGA_EX = 4


class AreaType(IntEnum):
    ALL = 0
    DECK = 1
    HAND = 2
    TRASH = 3
    ACTIVE = 4
    BENCH = 5
    PRIZE = 6
    STADIUM = 7
    ENERGY = 8
    TOOL = 9
    PRE_EVOLUTION = 10
    PLAYER = 11
    LOOKING = 12
    PLAYING = 13
    DECK_BOTTOM = 14
    ME = 15
    EFFECTED = 16
    EFFECTED_PRE_TARGET = 17
    SELECTED_LIST = 18
    TRIGGER_SUBJECT = 19
    TRIGGER_OBJECT = 20
    ATTACH = 21
    TURN_PLAY = 22
    ATTACK_PRE_MY_TURN = 23
    TEMPORARY = 24


class BadStatusType(IntEnum):
    NONE = 0
    ASLEEP = 1
    PARALYZED = 2
    CONFUSED = 3


class SelectSpecialConditionType(IntEnum):
    POISON = 0
    BURN = 1
    SLEEP = 2
    PARALYZE = 3
    CONFUSE = 4


class CardType(IntEnum):
    POKEMON = 0
    ITEM = 1
    TOOL = 2
    SUPPORTER = 3
    STADIUM = 4
    BASIC_ENERGY = 5
    SPECIAL_ENERGY = 6


class SpecialConditionType(IntEnum):
    POISON = 0
    BURN = 1
    SLEEP = 2
    PARALYZE = 3
    CONFUSE = 4


class EvolutionType(IntEnum):
    NO_EVOLUTION_TYPE = 0
    BASIC = 1
    STAGE1 = 2
    STAGE2 = 3
