"""IntEnum transcription of the CABT engine's real enums.

Source: engine/Types.h — verified against the actual engine source.
"""

from enum import IntEnum


def safe(cls: type[IntEnum], value: int | None) -> IntEnum | int | None:
    """Return the enum member for ``value``, or the raw int if unknown."""
    if value is None:
        return None
    try:
        return cls(value)
    except ValueError:
        return value


class SelectType(IntEnum):
    MAIN = 0
    CARD = 1
    ATTACHED_CARD = 2
    CARD_OR_ATTACHED_CARD = 3
    ENERGY = 4
    SKILL = 5
    ATTACK = 6
    EVOLVE = 7
    COUNT = 8
    YES_NO = 9
    SPECIAL_CONDITION = 10


class OptionType(IntEnum):
    NUMBER = 0
    YES = 1
    NO = 2
    CARD = 3
    TOOL_CARD = 4
    ENERGY_CARD = 5
    ENERGY = 6
    PLAY = 7
    ATTACH = 8
    EVOLVE = 9
    ABILITY = 10
    DISCARD = 11
    RETREAT = 12
    ATTACK = 13
    END = 14
    SKILL = 15
    SPECIAL_CONDITION = 16


class SelectContext(IntEnum):
    MAIN = 0
    SETUP_ACTIVE_POKEMON = 1
    SETUP_BENCH_POKEMON = 2
    SWITCH = 3
    TO_ACTIVE = 4
    TO_BENCH = 5
    TO_FIELD = 6
    TO_HAND = 7
    DISCARD = 8
    TO_DECK = 9
    TO_DECK_BOTTOM = 10
    TO_PRIZE = 11
    NOT_MOVE = 12
    DAMAGE_COUNTER = 13
    DAMAGE_COUNTER_ANY = 14
    DAMAGE = 15
    REMOVE_DAMAGE_COUNTER = 16
    HEAL = 17
    EVOLVES_FROM = 18
    EVOLVES_TO = 19
    DEVOLVE = 20
    ATTACH_FROM = 21
    ATTACH_TO = 22
    DETACH_FROM = 23
    LOOK = 24
    EFFECT_TARGET = 25
    DISCARD_ENERGY_CARD = 26
    DISCARD_TOOL_CARD = 27
    SWITCH_ENERGY_CARD = 28
    DISCARD_CARD_OR_ATTACHED_CARD = 29
    DISCARD_ENERGY = 30
    TO_HAND_ENERGY = 31
    TO_DECK_ENERGY = 32
    SWITCH_ENERGY = 33
    SKILL_ORDER = 34
    ATTACK = 35
    DISABLE_ATTACK = 36
    EVOLVE = 37
    DRAW_COUNT = 38
    DAMAGE_COUNTER_COUNT = 39
    REMOVE_DAMAGE_COUNTER_COUNT = 40
    IS_FIRST = 41
    MULLIGAN = 42
    ACTIVATE = 43
    FIRST_EFFECT = 44
    MORE_DEVOLVE = 45
    COIN_HEAD = 46
    AFFECT_SPECIAL_CONDITION = 47
    RECOVER_SPECIAL_CONDITION = 48


class AreaType(IntEnum):
    ALL = 0
    DECK = 1
    HAND = 2
    TRASH = 3
    ACTIVE = 4
    BENCH = 5
    PRIZE = 6
    STADIUM = 7
    ENERGY = 8
    TOOL = 9
    PRE_EVOLUTION = 10
    PLAYER = 11
    LOOKING = 12
    PLAYING = 13
    DECK_BOTTOM = 14
    ME = 15
    EFFECTED = 16
    EFFECTED_PRE_TARGET = 17
    SELECTED_LIST = 18
    TRIGGER_SUBJECT = 19
    TRIGGER_OBJECT = 20
    ATTACH = 21
    TURN_PLAY = 22
    ATTACK_PRE_MY_TURN = 23
    TEMPORARY = 24


class EnergyType(IntEnum):
    COLORLESS = 0
    GRASS = 1
    FIRE = 2
    WATER = 3
    LIGHTNING = 4
    PSYCHIC = 5
    FIGHTING = 6
    DARKNESS = 7
    METAL = 8
    DRAGON = 9
    RAINBOW = 10
    TEAM_ROCKET = 11
    PSYCHIC_DARKNESS = 12


class CardType(IntEnum):
    POKEMON = 0
    ITEM = 1
    TOOL = 2
    SUPPORTER = 3
    STADIUM = 4
    BASIC_ENERGY = 5
    SPECIAL_ENERGY = 6


class SpecialConditionType(IntEnum):
    POISON = 0
    BURN = 1
    SLEEP = 2
    PARALYZE = 3
    CONFUSE = 4


class BadStatusType(IntEnum):
    NONE = 0
    ASLEEP = 1
    PARALYZED = 2
    CONFUSED = 3


class PokemonType(IntEnum):
    NOT_POKEMON = 0
    NORMAL = 1
    POKEMON_ITEM = 2
    EX = 3
    MEGA_EX = 4


class EvolutionType(IntEnum):
    NO_EVOLUTION_TYPE = 0
    BASIC = 1
    STAGE1 = 2
    STAGE2 = 3


class TargetType(IntEnum):
    ALL = 0
    HP = 1
    MAX_HP = 2
    RETREAT_COST = 3
    ENERGY_TYPE = 4
    ENERGY_TYPE_2 = 5
    RESISTANCE = 6
    POKEMON_CARD = 7
    BASIC_POKEMON = 8
    EVOLVED_POKEMON = 9
    STAGE1 = 10
    STAGE2 = 11
    BASIC_ENERGY = 12
    SPECIAL_ENERGY = 13
    ENERGY_CARD = 14
    ITEM = 15
    TOOL = 16
    SUPPORTER = 17
    STADIUM = 18
    TRAINER = 19
    CARD_ID = 20
    POKEMON_OR_BASIC_ENERGY = 21
    BASIC_POKEMON_OR_BASIC_ENERGY = 22
    NOT_RULE_POKEMON_CARD_OR_BASIC_ENERGY = 23
    ENERGY_TYPE_POKEMON_OR_STADIUM = 24
    ITEM_OR_TOOL = 25
    ENEMY_TOOL_OR_SPECIAL_ENERGY_OR_STADIUM = 26
    ETHAN_POKEMON_OR_BASIC_FIRE_ENERGY = 27
    HAS_ABILITY = 28
    HAS_ABILITY_NAME = 29
    HAS_ATTACK_NAME = 30
    RULE_POKEMON = 31
    NOT_RULE_POKEMON = 32
    EX = 33
    MEGA_EX = 34
    TERASTAL = 35
    ANCIENT = 36
    FUTURE = 37
    HOP = 38
    LILLIE = 39
    IONO = 40
    N = 41
    ETHAN = 42
    CYNTHIA = 43
    MISTY = 44
    ARVEN = 45
    STEVEN = 46
    MARNIE = 47
    ERIKA = 48
    LARRY = 49
    TEAM_ROCKET = 50
    SILCOON_OR_CASCOON = 51
    KOFFING_OR_WEEZING = 52
    HONEDGE_OR_DOUBLADE_OR_AEGISLASH = 53
    NAME = 54
    NAME_CONTAINS = 55
    CAN_EVOLVE = 56
    CAN_EVOLVE_2 = 57
    CAN_EVOLVE_ME = 58
    CAN_EVOLVE_CONTEXT_CARD = 59
    CAN_EVOLVES_TO_CONTEXT_CARD = 60
    CAN_EVOLVE_FIELD = 61
    CAN_EVOLVE_FIELD_NOT_APPEAR_THIS_TURN = 62
    EVOLVED = 63
    EVOLVED_THIS_TURN_NAME = 64
    NOT_APPEAR_THIS_TURN = 65
    HEAL_THIS_TURN = 66
    ATTACHED_ME = 67
    ATTACHED_EFFECTED = 68
    ATTACHED_TRIGGER_SUBJECT = 69
    ATTACHED_TRIGGER_OBJECT = 70
    ATTACHED_CONTEXT_CARD = 71
    ATTACHED_ACTIVE_POKEMON = 72
    ATTACHED_BENCH_POKEMON = 73
    IS_ATTACHED_ENERGY = 74
    ATTACHED_ENERGY_COUNT = 75
    IS_ATTACHED_SPECIAL_ENERGY = 76
    IS_ATTACHED_ENERGY_TYPE = 77
    IS_ATTACHED_ENERGY_2_TYPE = 78
    IS_ATTACHED_ENERGY_NAME = 79
    IS_ATTACHED_TOOL = 80
    IS_ATTACHED_TOOL_NAME = 81
    IS_ATTACHED_TOOL_OR_SPECIAL_ENERGY = 82
    NOT_CONTEXT_CARD_ATTACHED_POKEMON = 83
    NOT_SELECTED_LIST_ATTACHED_POKEMON = 84
    ENERGY_TYPE_ATTACHED = 85
    REVERSE = 86
    AREA = 87
    TRIGGER_SUBJECT = 88
    TRIGGER_OBJECT = 89
    DAMAGE_COUNTER = 90
    MIN_HP = 91
    SAME_TYPE_ENEMY = 92
    SPECIAL_CONDITION = 93
    SPECIAL_CONDITION_OR_DAMAGED = 94
    POISON = 95
    BURN = 96
    CONFUSE = 97
    POISON_OR_BURN = 98
    BENCH_TO_ACTIVE_THIS_TURN = 99
    SAME_NAME_ENEMY_FIELD = 100
    NOT_CHECKED = 101


class TriggerType(IntEnum):
    NONE = 0
    TURN_END = 1
    POKEMON_CHECKUP = 2
    HAND_TO_BENCH = 3
    ACTIVE_TO_BENCH = 4
    TO_BENCH_MY_TURN = 5
    BENCH_TO_ACTIVE = 6
    DECK_TO_TRASH_ENEMY_EFFECT = 7
    EVOLVE_FROM_HAND = 8
    ENERGY_ATTACH_FROM_HAND = 9
    DAMAGED_ENEMY_ATTACK = 10
    DAMAGED_ENEMY_ATTACK_ACTIVE = 11
    PRE_KO = 12
    PRE_KO_FULL = 13
    PRE_KO_FULL_ENEMY = 14
    KO = 15
    KO_ENEMY_ATTACK_DAMAGE = 16
    KO_ENEMY_EX_ATTACK_DAMAGE = 17
    KO_ENEMY_ATTACK_DAMAGE_ACTIVE = 18
    PRE_RETREAT = 19
    ATTACH = 20


class EffectSelectType(IntEnum):
    ALL = 0
    CARD_COUNT = 1
    MAX_CARD_COUNT = 2
    CARD_UNTIL = 3
    MAX_CARD_UNTIL = 4
    ENERGY = 5
    MAX_ENERGY_CARD = 6
    TOOL_CARD = 7
    CARD_OR_ATTACHED_CARD_COUNT = 8
    EVOLVE = 9
    EVOLVE_2 = 10
